name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - develop
env:
  HELLO: 0
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v3
      - name: run number with offset
        run: |
          export HELLO=$(($HELLO+1)) && echo $HELLO >> $HELL0
