name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - develop
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest
   
   steps:
      - uses: actions/checkout@v3
      - name: Build and tag 
        id: tag_version
        run: |
          export FINAL_VERSION=$(cat setup.py | grep version | awk -F"'" '{ print $2 }') && echo $FINAL_VERSION
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(cat setup.py | grep version | awk -F"'" '{ print $2 }')" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT


