name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - develop
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest
   env:
      BUILD_NO: 0
   steps:
      - uses: actions/checkout@v3
      - name: run number with offset
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+200))
      - run: echo $GITHUB_RUN_NUMBER_WITH_OFFSET
 
