name: CI

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Build and tag 
        id: tag_version
        run: |
          export VERSION=$(cat setup.py | grep version | awk -F"'" '{ print $2 }') 
          export FINAL_VERSION="$(echo $VERSION | cut -d' ' -f1)" && echo $FINAL_VERSION
          export GIT_URL="$(echo $VERSION | cut -d' ' -f2)" && echo $GIT_URL
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=FINAL_VERSION::v$FINAL_VERSION"
          echo "::set-output name=GIT_URL::$GIT_URL"
          
      - name: tag_main
        if: ${{ steps.tag_version.outputs.branch }} == 'refs/heads/main'
        id: create_tag_main
        run: |
          git config --global user.email "mamthavathar2000@gmail.com"
          git config --global user.name "mamthamv"
          git tag -a ${{ steps.tag_version.outputs.FINAL_VERSION }} -m "Creating final release tags"
          git tag # Show the tagged commits
          git remote set-url origin ${{ steps.tag_version.outputs.GIT_URL }}
          git push origin --tags # Push all tags to GitHub.
          
      - name: release_main
        if: ${{ steps.tag_version.outputs.branch }} == 'refs/heads/main'
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.tag_version.outputs.FINAL_VERSION }}
          tag_name: ${{ steps.tag_version.outputs.FINAL_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
 
