name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Build and tag 
        id: tag_version
        run: |
          export FINAL_VERSION=$(cat setup.py | grep version | awk -F"'" '{ print $2 }') && echo $FINAL_VERSION
          git config user.email "mamthavathar2000@gmail.com"
          git config user.name "mamthamv"
          GIT_URL="https://github.com/mamthamv/version_tag.git"
          echo GIT_URL = $GIT_URL
          git tag -a ${FINAL_VERSION} -m "Creating final release tag"
          git tag # Show the tagged commits
          git remote set-url origin ${GIT_URL}
          git push origin --tags # Push all tags to GitHub.
          curl --data '{"tag_name": "v$FINAL_VERSION",
                "target_commitish": "master",
                "name": "v$FINAL_VERSION",
                "body": "Release of version $FINAL_VERSION",
                "draft": false,
                "prerelease": false}' https://api.github.com/repos/$OWNER/$REPOSITORY/releases
          gh auth login
          gh release create v1.2.3 --notes "bugfix release"
#git push ${GIT_URL} ${CI_BUILD_REF_NAME} --tags
      
