name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - main
     - develop
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Build and tag 
        id: tag_version
        run: |
          export FINAL_VERSION=$(cat setup.py | grep version | awk -F"'" '{ print $2 }') && echo $FINAL_VERSION 
          git config --global user.email "mamthavathar2000@gmail.com"
          git config --global user.name "mamthamv"
          if: ${{ GITHUB_REF#refs/heads/ == 'main' }}
          git tag -a $FINAL_VERSION -m "Creating final release tags"
          git tag # Show the tagged commits
          git remote set-url origin ${{ git config --get remote.origin.url }}
          git push origin --tags # Push all tags to GitHub.
          
      
