name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
     - main
     - develop
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Build and tag 
        id: tag_version
        run: |
           echo FINAL_VERSION=$(cat setup.py | grep version | awk -F"'" '{ print $2 }') >> $GITHUB_ENV
           echo BRANCH= ${GITHUB_REF#refs/heads/} >> $GITHUB_ENV
           echo BUILD_NO=1  >> $GITHUB_ENV
      
      - name: tag_main
        id: create_tag_main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "mamthavathar2000@gmail.com"
          git config --global user.name "mamthamv"
          if ${{ env.BRANCH}} == 'main'; then
            git tag -a ${{ env.FINAL_VERSION }} -m "Creating final release tags"
          else
            git tag -a "${{ env.FINAL_VERSION }}b.${{env.BUILD_NO}}" -m "Creating final release tagss"
            echo BUILD_NO=$((${{env.BUILD_NO}}+1)) >> $GITHUB_ENV
          fi
          git tag # Show the tagged commits
          git push origin --tags # Push all tags to GitHub.
          echo ${{env.BUILD_NO}}
      
     
      
