name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - name: Build and tag 
        id: tag_version
        run: |
          export VERSION=$(cat setup.py | grep version | awk -F"'" '{ print $2 }') 
          export FINAL_VERSION="$(echo $VERSION | cut -d' ' -f1)" && echo $FINAL_VERSION
          export GIT_URL="$(echo $VERSION | cut -d' ' -f2)" && echo $GIT_URL
          git config --global user.email "mamthavathar2000@gmail.com"
          git config --global user.name "mamthamv"
          git tag -a ${FINAL_VERSION} -m "Creating final release tag"
          git tag # Show the tagged commits
          git remote set-url origin ${GIT_URL}
          git push origin --tags # Push all tags to GitHub.
          gh release create v1.2.3 --notes "bugfix "
        
#git push ${GIT_URL} ${CI_BUILD_REF_NAME} --tags
      
